# Generated by Django 4.1 on 2023-12-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='')),
                ('url_or_path', models.CharField(max_length=2048, verbose_name='')),
                ('new_tab', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'verbose_name': 'Menu link',
                'verbose_name_plural': 'Menu links',
            },
        ),
    ]
