# Generated by Django 4.1 on 2023-12-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=False, verbose_name='New tab?'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='url_or_path',
            field=models.CharField(max_length=2048, verbose_name='Url or parth'),
        ),
    ]
