# Generated by Django 4.1 on 2023-12-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0003_sitesetup_alter_menulink_url_or_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
