# Generated by Django 4.1 on 2023-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0005_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon', verbose_name='Icon'),
        ),
    ]
