# Generated by Django 4.1 on 2023-12-30 15:18

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0006_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', help_text='A imagem deve ser .png', upload_to='assets/favicon', validators=[utils.model_validators.validate_png], verbose_name='Icon'),
        ),
    ]
